---
- name: Lab Playbook
  hosts: all
  become: true
  tasks:
    - name: Apache
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
      when: ansible_facts ['os_family'] == "Debian"
    - name: Apache2
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts ['os_family'] == "RedHat"
    - name: Start apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts ['os_family'] == "Debian"
    - name: Start apache2
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts ['os_family'] == "RedHat"
    - name: Install unzip
      ansible.builtin.yum:
        name: unzip
        state: present
      when: ansible_facts ['os_family'] == "RedHat"
    - name: Unzip
      ansible.builtin.unarchive:
        src: /home/tux/Downloads/2048.zip
        dest: /var/www/html/
        owner: root
        group: root
    - name: mariadb
      ansible.builtin.apt:
        name: mariadb-server
        state: present
      when: ansible_facts ['os_family'] == "Debian"
    - name: mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present
      when: ansible_facts ['os_family'] == "RedHat"
    - name: htop
      ansible.builtin.apt:
        name: htop
        state: absent
      when: ansible_facts ['os_family'] == "Debian"
    - name: htop
      ansible.builtin.yum:
        name: htop
        state: absent
      when: ansible_facts ['os_family'] == "RedHat"
