---
- name: 1st PB
  hosts: all
  become: true
  tasks:
    - name: Apache
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: Install unzip
      ansible.builtin.yum:
        name: unzip
        state: present 
    - name: Unzip
      ansible.builtin.unarchive:
        src: /home/tux/Downloads/2048.zip
        dest: /var/www/html/
        owner: root
        group: root
    - name: mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: htop
      ansible.builtin.yum:
        name: htop
        state: absent
